### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by FrannDzs**
Hi, how are you? I've been revising the translation and improved it a bit. I noticed that some translation strings are missing. Another thing I want to ask you is, is there a possibility to offer Dynamic Surrounding support? Because I want to be inside a house and go out the audio to be heard encapsulated, you know what I mean? good night! (on this side it's night time) greetings!

### CODE REVIEW

**Comment by MORIMORI0317** [comment]
Thankyou!

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings
Does Dynamic Surrounding mean this mod?

**Comment by FrannDzs** [comment]
> https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings
> Does Dynamic Surrounding mean this mod?

Yes, it is possible to merge them in some way? I don't know if it would really work, it's just an idea. Greetings!

**Comment by MORIMORI0317** [comment]
We plan to add options for deleting and sorting songs and playlists.

https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/dsurround/data/twilightforest.json
Dynamic Surroundings seems to be able to add data with a json file like this, so I will add it

**Comment by FrannDzs** [comment]
> We plan to add options for deleting and sorting songs and playlists.
> 
> https://github.com/OreCruncher/DynamicSurroundings/blob/master/src/main/resources/assets/dsurround/dsurround/data/twilightforest.json
> Dynamic Surroundings seems to be able to add data with a json file like this, so I will add it

Great! There is nothing like hearing good news in the morning :), I think the future of your mod is very promising. Greetings!

**Pull request merged**
